### ISSUE TITLE
offline usage

### ISSUE THREAD

**Issue by magdesign** [genescu/rust-currency-exchange#1]
thanks for this nice tool!

i am using it on my linux mobile phone, but it does only work when online. any chance to cache the exchange rates for offline usage until we are online again?

**Comment by genescu** [comment]
Hi @magdesign,

Implemented feature to fetch new exchange rates if your device is online; otherwise, fallback to cached file. 

Mfg

**Comment by magdesign** [comment]
wow... thank you so much for adding this feature in such a quick timeframe 🚀
